### ISSUE TITLE
[Bug] Install failure of nodejs resources

### ISSUE THREAD

**Issue by Anan5a** [HDInnovations/UNIT3D-Community-Edition#1268]
**Describe the bug**
Failed to complete ```npm install``` processs

**To Reproduce**
1. Go to 'newly cloned directory'
2. Follow manual install process 
3. See error

**Expected behavior**
Install the npm resources

**Screenshots**
![Screenshot from 2020-04-10 15-43-03](https://user-images.githubusercontent.com/16373480/78981820-9967dc00-7b42-11ea-8083-925649acfa88.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version: git master
- Laravel Version: 6
- PHP Version: 7.3
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**

**Comment by Anan5a** [comment]
## Update

After deleting packages-lock file I end up with this error

```log
npm verb stack     at JSON.parse (<anonymous>)
npm verb stack     at parseJson (/home/ananta/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
npm verb stack     at consumeBody.call.then.buffer (/home/ananta/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
npm verb stack     at <anonymous>
npm verb stack     at process._tickCallback (internal/process/next_tick.js:189:7)
npm verb cwd /home/ananta/PROJECTS/unit3d-test
npm verb Linux 4.19.0-8-amd64
npm verb argv "/home/ananta/.nvm/versions/node/v8.17.0/bin/node" "/home/ananta/.nvm/versions/node/v8.17.0/bin/npm" "install" "--verbose"
npm verb node v8.17.0
npm verb npm  v6.14.4
npm ERR! Unexpected end of JSON input while parsing near '...1.5.0","chokidar-cli"'
npm verb exit [ 1, true ]
npm timing npm Completed in 268165ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ananta/.npm/_logs/2020-04-10T10_28_50_049Z-debug.log
```

**Comment by HDVinnie** [comment]
OS?

**Comment by Anan5a** [comment]
Debian 10
I have another update.
After using node v13.x.x  (via nvm) these errors went away. But another error comes
```ab() never called ``` And no matter what everything ends up there

**Comment by HDVinnie** [comment]
I cannot help with Debian install. We recommend and support UNIT3D with Ubuntu 16 or 18 at the moment.

**Comment by Anan5a** [comment]
:(
But node is supposed to work equally between  both of them. I'll try ubuntu as well

**Comment by Anan5a** [comment]
@HDVinnie Here you go
```Ubuntu Server 18 LTS```

And npm logs
```
npm http fetch GET 200 https://registry.npmjs.org/laravel-mix/-/laravel-mix-5.0.4.tgz 386107ms
npm http fetch GET 200 https://registry.npmjs.org/sass/-/sass-1.26.3.tgz 395283ms
npm http fetch GET 200 https://registry.npmjs.org/yargs/-/yargs-13.2.4.tgz 395072ms
npm http fetch GET 200 https://registry.npmjs.org/yargs/-/yargs-12.0.5.tgz 401499ms
npm http fetch GET 200 https://registry.npmjs.org/npm-check-updates/-/npm-check-updates-4.1.0.tgz 403238ms
npm http fetch GET 200 https://registry.npmjs.org/cacache/-/cacache-15.0.0.tgz 402632ms
npm http fetch GET 200 https://registry.npmjs.org/webpack-cli/-/webpack-cli-3.3.11.tgz 509030ms
npm timing npm Completed in 523513ms
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-11T06_01_13_326Z-debug.log
root@ubuntu-virt-test:/var/www/html/UNIT3D# 
```
Same result as ```Debian 10```

**Comment by HDVinnie** [comment]
This is an issue with NPM. Not UNIT3D. I suggest you try running
```
sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npm run prod
```

**Comment by Anan5a** [comment]
@HDVinnie  done that multiple time already with no outcome change. Trying yarn now

**Comment by Anan5a** [comment]
## Update
```yarn``` successfully installed all packages without any hiccup.
 now ```npm run prod``` is showing bellow msg
```

> @ prod /var/www/html/UNIT3D
> npm run production


> @ production /var/www/html/UNIT3D
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

```
Is it the expected behavior?

**Comment by Anan5a** [comment]
## Update
Supervisor is not able to run laravel-echo-server. I get this error
```
root@ubuntu-virt-test:/var/www/html/UNIT3D# supervisorctl
unit3d-queue:unit3d-queue_00           RUNNING   pid 6824, uptime 0:00:02
unit3d-queue:unit3d-queue_01           RUNNING   pid 6823, uptime 0:00:02
unit3d-socket-io:unit3d-socket-io_00   FATAL   Exited too quickly (process log may have details)
```

**Comment by Anan5a** [comment]
Closing this because the issue is solved by using ```yarn```
