### ISSUE TITLE
missing script: prod after updating the application

### ISSUE THREAD

**Issue by mdelane7** [HDInnovations/UNIT3D-Community-Edition#1545]
Hey,

I had installed V5.0.0 and I saw some files were updated recently.. I ran "php artisan git:update"  Everything was fine expect the error called "npm ERR! missing script: prod" . Even When I tried to run "npm run prod", it says the same error. It was very fine before even I tested it about an hour ago but during update, this error occurred.

Here is the complete log of npm 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'prod' ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose stack Error: missing script: prod
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd /var/www/html
6 verbose Linux 5.4.0-56-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "prod"
8 verbose node v14.15.1
9 verbose npm  v6.14.8
10 error missing script: prod
11 verbose exit [ 1, true ]
```

Current Configuration:

OS: Ubuntu 20.04
RAM: 2444Mhz 16GB
CPU: 4C/8T 
UNIT3D: Latest (5.0.0)

Thanks for any kind of help :)

**Comment by mdelane7** [comment]
#1539 is the solution....

Sorry about creating the issue.
