### ISSUE TITLE
[Bug] Igdb not feching meta

### ISSUE THREAD

**Issue by maxpayneovh** [HDInnovations/UNIT3D-Community-Edition#1925]
**Describe the bug**
Attempt to read property "image_id" on array (View: /var/www/html/resources/views/torrent/partials/game_meta.blade.php) (View: /var/www/html/resources/views/torrent/partials/game_meta.blade.php)

` <?php $igdb_poster = (isset($meta) && $meta->cover) ? 'https://images.igdb.com/igdb/image/upload/t_original/'.$meta->cover->image_id.'.jpg' : 'https://via.placeholder.com/400x600'; ?>`

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.3.0
- Laravel Version: Ver. 8.61.0
- PHP Version: php8.0.10
- Database Driver & Version: mysql
- OS Driver and Version: Ubuntu 20

images.igdb.com/igdb/image/upload/t_cover_big/co1n1e.jpg
releasename: Yuppie.Psycho-PLAZA 
igbd_id: 26565

`Attempt to read property  "image_id" on array (View:  /var/www/html/resources/views/torrent/partials/game_meta.blade.php)  (View:  /var/www/html/resources/views/torrent/partials/game_meta.blade.php)  {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code:  0): Attempt to read property \"image_id\" on array (View:  /var/www/html/resources/views/torrent/partials/game_meta.blade.php)  (View:  /var/www/html/resources/views/torrent/partials/game_meta.blade.php) at  /var/www/html/storage/framework/views/3dead33457d1be4744803650a5092998cb7a385a.php:4`

[stacktrace]
#0 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(72): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Livewire\\LivewireViewCompilerEngine->handleViewException()
#2 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(794): Illuminate\\Http\\Response->__construct()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /var/www/html/app/Http/Middleware/CheckIfBanned.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckIfBanned->handle()
#15 /var/www/html/app/Http/Middleware/TwoStepAuth.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\TwoStepAuth->handle()
#17 /var/www/html/app/Http/Middleware/SetLanguage.php(101): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SetLanguage->handle()
#19 /var/www/html/app/Http/Middleware/UpdateLastAction.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\UpdateLastAction->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\\DisableBrowserCache->handle()
#47 /var/www/html/app/Http/Middleware/Http2ServerPush.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Http2ServerPush->handle()
#49 /var/www/html/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware->handle()
#51 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#53 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#68 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#69 {main}

**Comment by maxpayneovh** [comment]
curl 'https://api.igdb.com/v4/games' \
> -d 'fields *; where id = 120157;' \
> -H 'Client-ID: b445ew89s23bpl2bmi9b4k47y6tm7m' \
> -H 'Authorization: Bearer atgd76fvqej4ouvtgvhxowu4tqxkpw' \
> -H 'Accept: application/json'
[
  {
    "id": 120157,
    "artworks": [
      39069
    ],
    "category": 2,
    "cover": 75442,
    "created_at": 1561303915,
    "external_games": [
      2044157,
      2070217
    ],
    "first_release_date": 1561334400,
    "franchises": [
      6
    ],
    "game_modes": [
      1
    ],
    "genres": [
      11,
      15
    ],
    "involved_companies": [
      80458,
      80459
    ],
    "name": "Battlefleet Gothic: Armada 2 - Chaos Campaign Expansion",
    "parent_game": 83844,
    "platforms": [
      6
    ],
    "player_perspectives": [
      2
    ],
    "release_dates": [
      171659
    ],
    "screenshots": [
      314344
    ],
    "similar_games": [
      8773,
      11666,
      16806,
      17130,
      24620,
      25311,
      31253,
      102057,
      107218,
      111187
    ],
    "slug": "battlefleet-gothic-armada-2-chaos-campaign-expansion",
    "storyline": "Cadia has fallen, but this is just the start of your Black Crusade. At the head of a fleet of Word Bearers, the most fervent servants of the Ruinous Powers, Malos Vrykan begins his campaign of chaos and destruction across the Aegis Occularis. His path is yours, how will you bring the galaxy to its knees?",
    "summary": "In a brand-new Chaos Grand Campaign, experience a whole new narrative in Battlefleet Gothic: Armada 2, charting your rise through the ranks of Chaos to become a true champion of the Dark Gods. New ships, unique missions, and their own campaign map mechanics make the Chaos campaign a fully-fledged upgrade to Battlefleet Gothic: Armada 2.\n\n- New Chaos grand campaign: To Serve The Dark Gods.\n- Begin by conquering the key system of Chinchare and spread your influence from there\n- Brand new story shows the fate of the Galaxy should Chaos dominate\n- Side arcs include each other race being overrun by the Dark Gods and their minions\n- Use unique map resources to summon gifts of Chaos to destroy your enemies\n- Master Chaos fleets and their associated powers, upgrades, and admirals",
    "tags": [
      18,
      268435467,
      268435471
    ],
    "themes": [
      18
    ],
    "updated_at": 1629075767,
    "url": "https://www.igdb.com/games/battlefleet-gothic-armada-2-chaos-campaign-expansion",
    "videos": [
      28320
    ],
    "websites": [
      109964,
      189710,
      194516
    ],
    "checksum": "d61100d8-36b0-3296-ee53-e3b4d1d93654"
  }

**Comment by maxpayneovh** [comment]
curl 'https://api.igdb.com/v4/covers' \
> -d 'fields *; where id = 75442;' \
> -H 'Client-ID: b445ew89s23bpl2bmi9b4k47y6tm7m' \
> -H 'Authorization: Bearer atgd76fvqej4ouvtgvhxowu4tqxkpw' \
> -H 'Accept: application/json'
[
  {
    "id": 75442,
    "alpha_channel": false,
    "animated": false,
    "game": 120157,
    "height": 519,
    "image_id": "co1m7m",
    "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1m7m.jpg",
    "width": 389,
    "checksum": "0d657c31-5438-1e12-91aa-5b8b2813707b"
  }
