### ISSUE TITLE
[Bug] Object of class App\Enums\UserGroups could not be converted to int

### ISSUE THREAD

**Issue by FuNFooKaS** [HDInnovations/UNIT3D-Community-Edition#2177]
### UNIT3D Version

6.0.5

### PHP & Platform

8.1.2  ubuntu0.20.04.3

### Laravel verion

9.5.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

it is in my error logs

### Description

no idea tbh  

### Stack trace & logs

```shell
[2022-04-01 00:00:35] prod.ERROR: Object of class App\Enums\UserGroups could not be converted to int {"exception":"[object] (ErrorException(code: 0): Object of class App\\Enums\\UserGroups could not be converted to int at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1088)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1088): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Query\\Builder->whereIntegerInRaw()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1710): Illuminate\\Database\\Eloquent\\Builder->forwardCallTo()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->__call()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2133): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2145): Illuminate\\Database\\Eloquent\\Model->__call()
#7 /var/www/html/app/Console/Commands/AutoDisableInactiveUsers.php(53): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoDisableInactiveUsers->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(989): Illuminate\\Console\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#21 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#22 {main}
"}
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
You must have changed your groups.

Make sure the IDs line up here:
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/app/Enums/UserGroups.php

**Comment by FuNFooKaS** [comment]
When adding new classes Uploader  got changed to a diff ID  changed it back  and no error as of yet i a sure it fixed it but i will wait till morning before i close,thank you for the help.

**Comment by FuNFooKaS** [comment]
still getting the error  here is how m classes are in the DB
![image](https://user-images.githubusercontent.com/76744422/161387808-f9c7f8d6-ce38-4032-9aae-95ed9f42a632.png)

**Comment by LokiThor2021** [comment]
Try removing the return type 
`enum UserGroups: int` => `enum UserGroups`
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/4eed0e836c6a7d5c4bd393ee6510f3c09e6091e1/app/Enums/UserGroups.php#L19

**Comment by HDVinnie** [comment]
Stale.
