### ISSUE TITLE
[Bug] Torrent featured, posteponed give an error 500

### ISSUE THREAD

**Issue by gamemnon** [HDInnovations/UNIT3D-Community-Edition#2219]
### UNIT3D Version

6.0.8

### PHP & Platform

8.1.5

### Laravel verion

9.9.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

If a torrent is postponed disable Featured flag

### Description

When a torrent is Featured and you postponed it for tag or something, when you return to homepage that give you an internal server error 500

### Stack trace & logs

```shell
[2022-04-30 09:02:10] prod.ERROR: Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1683)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1683): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/app/Console/Commands/AutoRevokePermissions.php(54): Illuminate\\Support\\Collection->offsetGet()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoRevokePermissions->handle()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#9 /var/www/html/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#11 /var/www/html/vendor/symfony/console/Application.php(989): Illuminate\\Console\\Command->run()
#12 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#13 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#16 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#17 {main}
"}
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
Your provided stack trace has nothing to do with error.
