### ISSUE TITLE
[Bug] Error when running daily backups

### ISSUE THREAD

**Issue by LostRager** [HDInnovations/UNIT3D-Community-Edition#2357]
### UNIT3D Version

6.3.0

### PHP & Platform

8.1.8

### Laravel verion

9.20.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Uncommenting` //$schedule->command('backup:run')->daily();` to run daily backups

### Description

Uncommented `//$schedule->command('backup:run')->daily();` to run daily backups, but it failed.

### Stack trace & logs

```shell
The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins

Output
======
<no output>

Error Output
============
mysqldump: Got error: 1045: Access denied for user 'unit3d'@'localhost' (using password: YES) when trying to connect
 {"exception":"[object] (Spatie\\DbDumper\\Exceptions\\DumpFailed(code: 0): The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins

Output
======
<no output>

Error Output
============
mysqldump: Got error: 1045: Access denied for user 'unit3d'@'localhost' (using password: YES) when trying to connect
 at /var/www/html/vendor/spatie/db-dumper/src/Exceptions/DumpFailed.php:14)
[stacktrace]
#0 /var/www/html/vendor/spatie/db-dumper/src/DbDumper.php(178): Spatie\\DbDumper\\Exceptions\\DumpFailed::processDidNotEndSuccessfully()
#1 /var/www/html/vendor/spatie/db-dumper/src/Databases/MySql.php(143): Spatie\\DbDumper\\DbDumper->checkIfDumpWasSuccessFul()
#2 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(274): Spatie\\DbDumper\\Databases\\MySql->dumpToFile()
#3 [internal function]: Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(723): Illuminate\\Support\\Arr::map()
#6 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(277): Illuminate\\Support\\Collection->map()
#7 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(188): Spatie\\Backup\\Tasks\\Backup\\BackupJob->dumpDatabases()
#8 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(160): Spatie\\Backup\\Tasks\\Backup\\BackupJob->createBackupManifest()
#9 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(58): Spatie\\Backup\\Tasks\\Backup\\BackupJob->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Backup\\Commands\\BackupCommand->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#18 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(28): Illuminate\\Console\\Command->run()
#19 /var/www/html/vendor/symfony/console/Application.php(998): Spatie\\Backup\\Commands\\BaseCommand->run()
#20 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"}
```

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by LostRager** [comment]
Fixed by adding `'add_extra_option' => '--password=' . env('DB_PASSWORD', ''),` to the database.php file

```
            'dump' => [
                'dump_binary_path' => '/usr/bin', // only the path, so without `mysqldump` or `pg_dump`
                'use_single_transaction',
                'timeout' => 60 * 10, // 10 minute timeout
                'add_extra_option' => '--password=' . env('DB_PASSWORD', ''),
            ],
```
