### ISSUE TITLE
[Bug] Error when activated autopruning user

### ISSUE THREAD

**Issue by gamemnon** [HDInnovations/UNIT3D-Community-Edition#2414]
### UNIT3D Version

6.4.0

### PHP & Platform

8.1.10

### Laravel verion

9.25.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Prune user every night.

### Description

After i activated user_pruning to True in pruning.php 
![Capture d’écran 2022-09-22 113047](https://user-images.githubusercontent.com/92171709/191936175-e21bf4fd-110c-43f0-9378-d6b6c9b12e94.png)
[UserGroups.txt](https://github.com/HDInnovations/UNIT3D-Community-Edition/files/9632626/UserGroups.txt)

### Stack trace & logs

```shell
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1088): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Query\\Builder->whereIntegerInRaw()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1861): Illuminate\\Database\\Eloquent\\Builder->forwardCallTo()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->__call()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2191): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2203): Illuminate\\Database\\Eloquent\\Model->__call()
#7 /var/www/html/app/Console/Commands/AutoDisableInactiveUsers.php(53): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoDisableInactiveUsers->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\\Container\\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(998): Illuminate\\Console\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#21 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#22 {main}
"}
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
@gamemnon whats the error above `[stacktrace]`?

**Comment by HDVinnie** [comment]
Closing due to no response. More info needed as stated above.
