### ISSUE TITLE
[Bug] The dump process failed with a none successful exitcode.

### ISSUE THREAD

**Issue by LostRager** [HDInnovations/UNIT3D-Community-Edition#2626]
### UNIT3D Version

6.5.0

### PHP & Platform

8.2.3

### Laravel verion

9.41.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Backup does not work on latest version of mysql (8.0.32-0ubuntu0.20.04.2)

### Description

Neither manual or automated backup works.

### Stack trace & logs

```shell
The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins

Output
======
<no output>

Error Output
============
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't execute 'FLUSH TABLES': Access denied; you need (at least one of) the RELOAD or FLUSH_TABLES privilege(s) for this operation (1227)
 {"exception":"[object] (Spatie\\DbDumper\\Exceptions\\DumpFailed(code: 0): The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins

Output
======
<no output>

Error Output
============
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't execute 'FLUSH TABLES': Access denied; you need (at least one of) the RELOAD or FLUSH_TABLES privilege(s) for this operation (1227)
 at /var/www/html/vendor/spatie/db-dumper/src/Exceptions/DumpFailed.php:14)
[stacktrace]
#0 /var/www/html/vendor/spatie/db-dumper/src/DbDumper.php(178): Spatie\\DbDumper\\Exceptions\\DumpFailed::processDidNotEndSuccessfully()
#1 /var/www/html/vendor/spatie/db-dumper/src/Databases/MySql.php(143): Spatie\\DbDumper\\DbDumper->checkIfDumpWasSuccessFul()
#2 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(274): Spatie\\DbDumper\\Databases\\MySql->dumpToFile()
#3 [internal function]: Spatie\\Backup\\Tasks\\Backup\\BackupJob->Spatie\\Backup\\Tasks\\Backup\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(739): Illuminate\\Support\\Arr::map()
#6 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(248): Illuminate\\Support\\Collection->map()
#7 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(188): Spatie\\Backup\\Tasks\\Backup\\BackupJob->dumpDatabases()
#8 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(160): Spatie\\Backup\\Tasks\\Backup\\BackupJob->createBackupManifest()
#9 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(58): Spatie\\Backup\\Tasks\\Backup\\BackupJob->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Backup\\Commands\\BackupCommand->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(147): Symfony\\Component\\Console\\Command\\Command->run()
#18 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(28): Illuminate\\Console\\Command->run()
#19 /var/www/html/vendor/symfony/console/Application.php(1014): Spatie\\Backup\\Commands\\BaseCommand->run()
#20 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#24 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"}
```

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by IamMika23** [comment]
Hello,
It's due to last mysqldump update. You must give RELOAD, PROCESS privileges to your mysql user.

```
sudo -u root mysql
GRANT RELOAD,PROCESS ON *.* TO 'unit3d_user'@'localhost';
```

**Comment by HDVinnie** [comment]
@LostRager the answer by @IamMika23 is correct. This is due to a change with `mysqldump` and not related to UNIT3D itself.
