### ISSUE TITLE
[Bug] 1213 Deadlock

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3476]
### UNIT3D Version

v7.2.5

### PHP & Platform

8.3.2-1+ubuntu22.04.1+deb.sury.org+1

### Laravel verion

10.42.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Gateway 504 and 502 errors with site, stack trace logs may be relevant

### Description

things had been going well for our users so we decided to open registration again. We did had an expected increase in traffic but nothing crazy.  cpu is not being over taxed and our traffic logs with host are nothing crazy.

but hte site started to get bogged down and going to lots of gateway errors.

the larval logs are now showing lots of deadlock issues now.   i wonder if the db is tying it self up in a loop somewhere.

didnt see deadlock errors in anything reported on here so made a ticket.

### Stack trace & logs

```shell
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (Connection: mysql, SQL: delete from `peers` where `active` = 0 and `updated_at` > 2024-02-04 04:33:38) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (Connection: mysql, SQL: delete from `peers` where `active` = 0 and `updated_at` > 2024-02-04 04:33:38) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(557): Illuminate\\Database\\Connection->affectingStatement()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3615): Illuminate\\Database\\Connection->delete()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1271): Illuminate\\Database\\Query\\Builder->delete()
#5 /var/www/html/app/Console/Commands/AutoDeleteStoppedPeers.php(43): Illuminate\\Database\\Eloquent\\Builder->delete()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoDeleteStoppedPeers->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#12 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#16 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#18 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}

[previous exception] [object] (PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:605)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(605): PDOStatement->execute()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(557): Illuminate\\Database\\Connection->affectingStatement()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3615): Illuminate\\Database\\Connection->delete()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1271): Illuminate\\Database\\Query\\Builder->delete()
#7 /var/www/html/app/Console/Commands/AutoDeleteStoppedPeers.php(43): Illuminate\\Database\\Eloquent\\Builder->delete()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoDeleteStoppedPeers->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#20 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"} 


SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (Connection: mysql, SQL: update `users` set `last_action` = 2024-02-04 06:50:42, `users`.`updated_at` = 2024-02-04 06:50:42 where `id` in (3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 989, 1097, 3, 989, 352, 3, 989, 989, 989, 321, 321) and `users`.`deleted_at` is null) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (Connection: mysql, SQL: update `users` set `last_action` = 2024-02-04 06:50:42, `users`.`updated_at` = 2024-02-04 06:50:42 where `id` in (3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 989, 1097, 3, 989, 352, 3, 989, 989, 989, 321, 321) and `users`.`deleted_at` is null) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\\Database\\Connection->affectingStatement()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3421): Illuminate\\Database\\Connection->update()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1059): Illuminate\\Database\\Query\\Builder->update()
#5 /var/www/html/app/Console/Commands/AutoUpdateUserLastActions.php(49): Illuminate\\Database\\Eloquent\\Builder->update()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoUpdateUserLastActions->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#12 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#16 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#18 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}

[previous exception] [object] (PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:605)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(605): PDOStatement->execute()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): Illuminate\\Database\\Connection->affectingStatement()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3421): Illuminate\\Database\\Connection->update()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1059): Illuminate\\Database\\Query\\Builder->update()
#7 /var/www/html/app/Console/Commands/AutoUpdateUserLastActions.php(49): Illuminate\\Database\\Eloquent\\Builder->update()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoUpdateUserLastActions->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#20 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"}
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
This isn't really a bug....either your server and deps are not tuned or your server is hot garbage. Or both......

**Comment by BitPyrate** [comment]
Do you have suggested things to check tuning on? 
It did seem to go away after a few hours even though we are under an even slightly heavier load now.. It might have been a datacenter issue.

**Comment by BitPyrate** [comment]
the issue has not returned may have been an anomaly. (we suspect the data center that hosted)
It sounds performance related from your response.
If you don't have any tips or recommended tuning, you can close the case because i cant contest it, and i can no longer reproduce the issue.

**Comment by HDVinnie** [comment]
> the issue has not returned may have been an anomaly. (we suspect the data center that hosted)
> It sounds performance related from your response.
> If you don't have any tips or recommended tuning, you can close the case because i cant contest it, and i can no longer reproduce the issue.

I cannot offer any cut and paste suggestions as each server is different. In order to scale properly MySQL, REDIS, PHP and NGINX and min should be tuned. I do offer tuning services.
