### ISSUE TITLE
[Bug]Redis _ error what is mean

### ISSUE THREAD

**Issue by leech24** [HDInnovations/UNIT3D-Community-Edition#3982]
### UNIT3D Version

v8.1.3

### PHP & Platform

php 8.3.8 - 8.0.37-0ubuntu0.20.04.3

### Laravel verion

11.5.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

website i think work ok
but this error came many time
i dnot know about what lexical 

i think if this error about Emil  bot work perfect

### Description

Redis

### Stack trace & logs

```shell
Wrong parameter count for Redis::sAdd() {"exception":"[object] (ArgumentCountError(code: 0): Wrong parameter count for Redis::sAdd() at /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Redis->sAdd()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(531): Illuminate\\Redis\\Connections\\Connection->command()
#2 /var/www/html/app/Console/Commands/AutoCacheRandomMediaIds.php(59): Illuminate\\Redis\\Connections\\PhpRedisConnection->command()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoCacheRandomMediaIds->handle()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call()
#9 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#11 /var/www/html/vendor/symfony/console/Application.php(1049): Illuminate\\Console\\Command->run()
#12 /var/www/html/vendor/symfony/console/Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand()
#13 /var/www/html/vendor/symfony/console/Application.php(169): Symfony\\Component\\Console\\Application->doRun()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1183): Illuminate\\Foundation\\Console\\Kernel->handle()
#16 /var/www/html/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#17 {main}
"}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3982">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3982/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3982/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
This was already fixed here and will be included in the next release: https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/3828
