### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sh4down** [HDInnovations/UNIT3D-Community-Edition#4287]
### UNIT3D Version

8.3.3

### PHP & Platform

8.3.12 ubuntu 22.04.01

### Laravel verion

11.28.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

When searching, return the titles of the year stating in the field

### Description

When searching by starting year or ending year, error 500 occurs

### Stack trace & logs

```shell
Attribute `movie.year` is not filterable. Available filterable attributes are: `anon fl_until free tv.genres.id bookmarks.user_id highspeed times_completed name featured history_inactive.user_id resolution.id category.movie_meta movie.genres.id du_until keywords region_id tvdb movie.companies.id tmdb id movie.name tv.name igdb history_active.user_id folder files.name playlists.id season_number created_at user.username user_id distributor_id tv.original_language type.id episode_number sticky seeders freeleech_tokens.user_id size movie.original_language deleted_at personal_release status category.tv_meta stream category.id info_hash imdb internal refundable history_seeders.user_id tv.id doubleup leechers movie.adult tv.companies.id tv.networks.id movie.id history_complete.user_id sd movie.collection.id mal history_leechers.user_id bumped_at history_incomplete.user_id`.
1:11 movie.year >= 2022 {"userId":13,"exception":"[object] (Meilisearch\\Exceptions\\ApiException(code: 400): Attribute `movie.year` is not filterable. Available filterable attributes are: `anon fl_until free tv.genres.id bookmarks.user_id highspeed times_completed name featured history_inactive.user_id resolution.id category.movie_meta movie.genres.id du_until keywords region_id tvdb movie.companies.id tmdb id movie.name tv.name igdb history_active.user_id folder files.name playlists.id season_number created_at user.username user_id distributor_id tv.original_language type.id episode_number sticky seeders freeleech_tokens.user_id size movie.original_language deleted_at personal_release status category.tv_meta stream category.id info_hash imdb internal refundable history_seeders.user_id tv.id doubleup leechers movie.adult tv.companies.id tv.networks.id movie.id history_complete.user_id sd movie.collection.id mal history_leechers.user_id bumped_at history_incomplete.user_id`.
1:11 movie.year >= 2022 at /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php:186)
[stacktrace]
#0 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(157): Meilisearch\\Http\\Client->parseResponse()
#1 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(95): Meilisearch\\Http\\Client->execute()
#2 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(207): Meilisearch\\Http\\Client->post()
#3 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(188): Meilisearch\\Endpoints\\Indexes->rawSearch()
#4 /var/www/html/app/Http/Livewire/TorrentSearch.php(492): Meilisearch\\Endpoints\\Indexes->search()
#5 [internal function]: App\\Http\\Livewire\\TorrentSearch->torrents()
#6 /var/www/html/vendor/livewire/livewire/src/helpers.php(57): ReflectionMethod->invoke()
#7 /var/www/html/vendor/livewire/livewire/src/Features/SupportComputed/BaseComputed.php(138): class@anonymous->__call()
#8 /var/www/html/vendor/livewire/livewire/src/Features/SupportComputed/BaseComputed.php(60): Livewire\\Features\\SupportComputed\\BaseComputed->evaluateComputed()
#9 /var/www/html/vendor/livewire/livewire/src/EventBus.php(60): Livewire\\Features\\SupportComputed\\BaseComputed->handleMagicGet()
#10 /var/www/html/vendor/livewire/livewire/src/helpers.php(98): Livewire\\EventBus->trigger()
#11 /var/www/html/vendor/livewire/livewire/src/Component.php(100): Livewire\\trigger()
#12 /var/www/html/app/Http/Livewire/TorrentSearch.php(802): Livewire\\Component->__get()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\TorrentSearch->render()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(271): Livewire\\Wrapped->__call()
#19 /var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(231): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->getView()
#20 /var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(104): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->render()
#21 /var/www/html/vendor/livewire/livewire/src/LivewireManager.php(97): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#22 /var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(94): Livewire\\LivewireManager->update()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#28 /var/www/html/vendor/hdvinnie/laravel-security-headers/src/SecureHeadersMiddleware.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): HDVinnie\\SecureHeaders\\SecureHeadersMiddleware->handle()
#30 /var/www/html/app/Http/Middleware/UpdateLastAction.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\UpdateLastAction->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequestsWithRedis.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Routing\\Middleware\\ThrottleRequestsWithRedis->handleRequest()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(89): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#58 /var/www/html/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#60 /var/www/html/app/Http/Middleware/BlockIpAddress.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\BlockIpAddress->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1188): Illuminate\\Foundation\\Http\\Kernel->handle()
#78 /var/www/html/public/index.php(19): Illuminate\\Foundation\\Application->handleRequest()
#79 {main}
"}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4287">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4287/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4287/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
You missed the maintenance steps described here: https://github.com/HDInnovations/UNIT3D-Community-Edition/wiki/Meilisearch-Setup-for-UNIT3D#3-maintenance

**Comment by HDVinnie** [comment]
Its also mentioned in release notes

https://github.com/HDInnovations/UNIT3D-Community-Edition/releases/tag/v8.3.3

**Comment by sh4down** [comment]
"I followed your update instructions carefully, except for running Meilisearch as the www-data user. I even redid the installation to make sure everything was set up correctly, but I'm still encountering the same error with the trumpable filter. Is there anything else you’d recommend I check?"

**Comment by sh4down** [comment]
> Its also mentioned in release notes
> 
> https://github.com/HDInnovations/UNIT3D-Community-Edition/releases/tag/v8.3.3

"I followed your update instructions carefully, except for running Meilisearch as the www-data user. I even redid the installation to make sure everything was set up correctly, but I'm still encountering the same error with the trumpable filter. Is there anything else you’d recommend I check?"

**Comment by HDVinnie** [comment]
> > Its also mentioned in release notes
> 
> > 
> 
> > https://github.com/HDInnovations/UNIT3D-Community-Edition/releases/tag/v8.3.3
> 
> 
> 
> "I followed your update instructions carefully, except for running Meilisearch as the www-data user. I even redid the installation to make sure everything was set up correctly, but I'm still encountering the same error with the trumpable filter. Is there anything else you’d recommend I check?"

Trumpable filter is know and different then your original issue. I suggest opening a new issue so it can be tracked properly.

**Comment by sh4down** [comment]
> > > Its also mentioned in release notes
> > 
> > 
> > > 
> > 
> > 
> > > https://github.com/HDInnovations/UNIT3D-Community-Edition/releases/tag/v8.3.3
> > 
> > 
> > "I followed your update instructions carefully, except for running Meilisearch as the www-data user. I even redid the installation to make sure everything was set up correctly, but I'm still encountering the same error with the trumpable filter. Is there anything else you’d recommend I check?"
> 
> Trumpable filter is known and different then your original issue. I suggest opening a new issue so it can be tracked properly.

Sure, I can open a new issue, but what I mean is that I have had both errors since before opening this issue. I failed to mention it because I thought they were part of the same problem. After updating to 8.3.3 I did the meilisearch process, but I still have the same problem, I even redid the step and the same error persists.

**Comment by sh4down** [comment]
@HDVinnie @Roardom 

After analyzing some files I found the problem, I don't know what happened but my `"config/scout.php" ` file was not updated to v8.3.3, after updating this file and synchronizing the torrents with the commands again `"sudo php artisan scout:sync-index-settings and sudo php artisan scout:import "App\Models\Torrent""`, everything went fine.

**Comment by HDVinnie** [comment]
> @HDVinnie @Roardom 
> 
> 
> 
> After analyzing some files I found the problem, I don't know what happened but my `"config/scout.php" ` file was not updated to v8.3.3, after updating this file and synchronizing the torrents with the commands again `"sudo php artisan scout:sync-index-settings and sudo php artisan scout:import "App\Models\Torrent""`, everything went fine.

Glad you figured it out. Only way that could happen during git updater is if said no instead of yes when replacing file
