### ISSUE TITLE
[Bug] Error 500 on torrents page

### ISSUE THREAD

**Issue by Lilmix** [HDInnovations/UNIT3D-Community-Edition#4389]
### UNIT3D Version

v8.3.4

### PHP & Platform

8.3.14 - ubuntu 22.04.1 x64

### Laravel verion

11.28.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Clicking the Torrents tab or navigating to domain.example.com/torrents will take you to the torrents tab

### Description

Recieve error screen
Error 500: Internal Server Error
Our server encountered an internal error. Sorry For The Inconvenience

### Stack trace & logs

```shell
cURL error 7: Failed to connect to localhost port 7700 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:7700/indexes/torrents {"exception":"[object] (Meilisearch\\Exceptions\\CommunicationException(code: 0): cURL error 7: Failed to connect to localhost port 7700 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:7700/indexes/torrents at /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php:159)
[stacktrace]
#0 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(71): Meilisearch\\Http\\Client->execute()
#1 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(129): Meilisearch\\Http\\Client->get()
#2 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(134): Meilisearch\\Endpoints\\Indexes->fetchRawInfo()
#3 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Delegates/HandlesIndex.php(32): Meilisearch\\Endpoints\\Indexes->fetchInfo()
#4 /var/www/html/app/Console/Commands/AutoSyncTorrentsToMeilisearch.php(51): Meilisearch\\Client->getIndex()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoSyncTorrentsToMeilisearch->handle()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#11 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle()
#18 /var/www/html/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#19 {main}

[previous exception] [object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 7: Failed to connect to localhost port 7700 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:7700/indexes/torrents at /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:275)
[stacktrace]
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(205): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(157): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(55): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\\HandlerStack->__invoke()
#11 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(106): GuzzleHttp\\Client->transfer()
#12 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(138): GuzzleHttp\\Client->sendAsync()
#13 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(157): GuzzleHttp\\Client->sendRequest()
#14 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(71): Meilisearch\\Http\\Client->execute()
#15 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(129): Meilisearch\\Http\\Client->get()
#16 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(134): Meilisearch\\Endpoints\\Indexes->fetchRawInfo()
#17 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Delegates/HandlesIndex.php(32): Meilisearch\\Endpoints\\Indexes->fetchInfo()
#18 /var/www/html/app/Console/Commands/AutoSyncTorrentsToMeilisearch.php(51): Meilisearch\\Client->getIndex()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoSyncTorrentsToMeilisearch->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#25 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#27 /var/www/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#28 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#29 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 /var/www/html/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#33 {main}
"}
```

**Comment by HDVinnie** [comment]
The public installer is archived. You need to manually install meilisearch.
